name: Buddj ~ Quality control

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      back: ${{ steps.filter.outputs.back }}
      front: ${{ steps.filter.outputs.front }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            back: 'back/**'
            front: 'front-v3/**'

  back_checks:
    needs: [ changes ]
    if: needs.changes.outputs.back == 'true'
    name: Back ~ Quality Checks
    runs-on: ubuntu-latest
    container: node:22.22.1-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v6

    - name: Back ~ Use Node
      uses: actions/setup-node@v6
      with:
        node-version: "22.22.1"

    - name: Back ~ Install
      working-directory: ./back
      run: npm install

    - name: Back ~ ESLint checks
      working-directory: ./back
      run: npm run lint

    - name: Back ~ Tests
      working-directory: ./back
      run: npm run tf
      env:
        DB_URL_TEST: postgres
        DB_PORT_TEST: 5432
        DB_USER_TEST: postgres
        DB_PASSWORD_TEST: postgres
        DB_NAME_TEST: postgres
        PORT: ${{ secrets.PORT }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        SCOPES: ${{ secrets.SCOPES }}
        SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        FRONT_URL: ${{ secrets.FRONT_URL }}
        FRONT_REDIRECT_URL: ${{ secrets.FRONT_REDIRECT_URL }}
        TEMPLATE: ${{ secrets.TEMPLATE }}
        YEARLY: ${{ secrets.YEARLY }}
        YEARLY_BUDGETS: ${{ secrets.YEARLY_BUDGETS }}

  front_checks:
    name: Front ~ Quality Checks
    needs: [ changes ]
    if: needs.changes.outputs.front == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Front ~ Use Node
      uses: actions/setup-node@v6
      with:
        node-version: "22.22.1"

    - name: Front ~ Install
      working-directory: ./front-v3
      run: npm install

    - name: Back ~ ESLint checks
      working-directory: ./front-v3
      run: npm run lint

    - name: Front ~ Build
      working-directory: ./front-v3
      run: npm run build

  back_CD:
    name: Back ~ Deployment
    needs: [ changes, back_checks, front_checks ]
    if: |
      always() &&
      github.event_name == 'push' && github.ref == 'refs/heads/main' &&
      needs.changes.outputs.back == 'true' &&
      needs.back_checks.result == 'success' &&
      (needs.front_checks.result == 'success' || needs.front_checks.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Deploy
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_API }}
      run: curl "$deploy_url"

  front_CD:
    name: Front ~ Deployment
    needs: [ changes, front_checks, back_CD ]
    if: |
      always() &&
      github.event_name == 'push' && github.ref == 'refs/heads/main' &&
      needs.changes.outputs.front == 'true' &&
      needs.front_checks.result == 'success' &&
      (needs.back_CD.result == 'success' || needs.back_CD.result == 'skipped')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Deploy
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_APP_v3 }}
      run: curl "$deploy_url"
